// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKy2s5vldWTHJyLsErTXU14DUw2TGO7M',
    appId: '1:342984756978:web:b331bbfdbc3e9b8d70ca6b',
    messagingSenderId: '342984756978',
    projectId: 'flutterfirebaseauthstudy',
    authDomain: 'flutterfirebaseauthstudy.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthstudy.firebasestorage.app',
    measurementId: 'G-CB63B4DV7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jMFu0kRldsoOvm-UI_G7Q1tvnUt4yZQ',
    appId: '1:342984756978:android:f26333d8262eabc270ca6b',
    messagingSenderId: '342984756978',
    projectId: 'flutterfirebaseauthstudy',
    storageBucket: 'flutterfirebaseauthstudy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw9So6oxmYmXU4KvqA9VUWmU5bjYjoeSg',
    appId: '1:342984756978:ios:d7db660bc5d53dba70ca6b',
    messagingSenderId: '342984756978',
    projectId: 'flutterfirebaseauthstudy',
    storageBucket: 'flutterfirebaseauthstudy.firebasestorage.app',
    iosBundleId: 'com.kenant42.flutterfirebaseauthstudy',
  );
}
